services:
  - type: web
    name: dovira
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: sh -c "php artisan optimize:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: DOVIRA
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://dovira-rl2o.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: APP_MAINTENANCE_DRIVER
        value: file
