[program:dovira-scheduler]
command=/usr/bin/php /var/www/dovira/current/artisan schedule:work
directory=/var/www/dovira/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/dovira/shared/storage/logs/scheduler.log
stopwaitsecs=360
