<?php

return [
    'nova-market' => [
        'name' => 'Nova Market',
        'logo_url' => 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Київ',
        'district' => 'Подільський район',
        'reviews_count' => 182,
        'rating' => 4.9,
        'recommend_percent' => 91,
        'verified' => true,
        'pro' => true,
        'website' => 'novamarket.ua',
        'email' => 'support@novamarket.ua',
        'phone' => '+380 67 111 22 33',
        'address' => 'Київ, вул. Межигірська, 12',
        'about' => 'Мережа міських супермаркетів із фокусом на швидку доставку та якісний клієнтський сервіс.',
    ],
    'tech-hub-store' => [
        'name' => 'TECH HUB Store',
        'logo_url' => 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Львів',
        'district' => 'Галицький район',
        'reviews_count' => 136,
        'rating' => 4.8,
        'recommend_percent' => 88,
        'verified' => true,
        'pro' => true,
        'website' => 'techhub.com.ua',
        'email' => 'hello@techhub.com.ua',
        'phone' => '+380 67 222 33 44',
        'address' => 'Львів, просп. Свободи, 19',
        'about' => 'Магазин електроніки з сервісною підтримкою, консультаціями та гарантійним супроводом.',
    ],
    'citydent-clinic' => [
        'name' => 'CityDent Clinic',
        'logo_url' => 'https://images.pexels.com/photos/3845810/pexels-photo-3845810.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Одеса',
        'district' => 'Приморський район',
        'reviews_count' => 94,
        'rating' => 4.9,
        'recommend_percent' => 90,
        'verified' => true,
        'pro' => false,
        'website' => 'citydent.ua',
        'email' => 'clinic@citydent.ua',
        'phone' => '+380 67 333 44 55',
        'address' => 'Одеса, вул. Канатна, 35',
        'about' => 'Стоматологічна клініка повного циклу: діагностика, лікування, протезування та профілактика.',
    ],
    'autocare-service' => [
        'name' => 'AutoCare Service',
        'logo_url' => 'https://images.pexels.com/photos/3807329/pexels-photo-3807329.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Дніпро',
        'district' => 'Шевченківський район',
        'reviews_count' => 78,
        'rating' => 4.7,
        'recommend_percent' => 85,
        'verified' => false,
        'pro' => false,
        'website' => 'autocare-service.ua',
        'email' => 'service@autocare-service.ua',
        'phone' => '+380 67 444 55 66',
        'address' => 'Дніпро, вул. Січових Стрільців, 8',
        'about' => 'Автосервіс для планового обслуговування та діагностики легкових авто.',
    ],
    'green-delivery' => [
        'name' => 'Green Delivery',
        'city' => 'Київ',
        'district' => 'Соломʼянський район',
        'reviews_count' => 59,
        'rating' => 4.6,
        'recommend_percent' => 84,
        'verified' => false,
        'pro' => false,
        'website' => 'greendelivery.ua',
        'email' => 'contact@greendelivery.ua',
        'phone' => '+380 67 555 66 77',
        'address' => 'Київ, вул. Польова, 4',
        'about' => 'Служба локальної доставки для e-commerce і малого бізнесу.',
    ],
    'smarthome-store' => [
        'name' => 'SmartHome Store',
        'city' => 'Харків',
        'district' => 'Шевченківський район',
        'reviews_count' => 101,
        'rating' => 4.8,
        'recommend_percent' => 89,
        'verified' => false,
        'pro' => true,
        'website' => 'smarthome.store',
        'email' => 'team@smarthome.store',
        'phone' => '+380 67 666 77 88',
        'address' => 'Харків, вул. Сумська, 54',
        'about' => 'Техніка та рішення для розумного дому: від підбору до встановлення.',
    ],
    'resto-family' => [
        'name' => 'Resto Family',
        'logo_url' => 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Вінниця',
        'district' => 'Центральний район',
        'reviews_count' => 67,
        'rating' => 4.7,
        'recommend_percent' => 86,
        'verified' => false,
        'pro' => false,
        'website' => 'restofamily.ua',
        'email' => 'manager@restofamily.ua',
        'phone' => '+380 67 777 88 99',
        'address' => 'Вінниця, вул. Соборна, 41',
        'about' => 'Мережа закладів із фокусом на стабільну якість сервісу та меню.',
    ],
    'bookflow' => [
        'name' => 'BookFlow',
        'city' => 'Черкаси',
        'district' => 'Соснівський район',
        'reviews_count' => 43,
        'rating' => 4.5,
        'recommend_percent' => 81,
        'verified' => false,
        'pro' => false,
        'website' => 'bookflow.ua',
        'email' => 'hi@bookflow.ua',
        'phone' => '+380 67 888 99 00',
        'address' => 'Черкаси, бул. Шевченка, 210',
        'about' => 'Онлайн-сервіс для бронювання послуг і запису до спеціалістів.',
    ],
    'freshcare-pharmacy' => [
        'name' => 'FreshCare Pharmacy',
        'city' => 'Полтава',
        'district' => 'Шевченківський район',
        'reviews_count' => 88,
        'rating' => 4.8,
        'recommend_percent' => 89,
        'verified' => true,
        'pro' => false,
        'website' => 'freshcare.ua',
        'email' => 'care@freshcare.ua',
        'phone' => '+380 67 909 10 11',
        'address' => 'Полтава, вул. Європейська, 24',
        'about' => 'Аптечна мережа з онлайн-замовленням і самовивозом.',
    ],
    'quickbox-delivery' => [
        'name' => 'QuickBox Delivery',
        'logo_url' => 'https://images.pexels.com/photos/7706457/pexels-photo-7706457.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
        'city' => 'Івано-Франківськ',
        'district' => 'Центральний район',
        'reviews_count' => 52,
        'rating' => 4.6,
        'recommend_percent' => 83,
        'verified' => false,
        'pro' => true,
        'website' => 'quickbox.delivery',
        'email' => 'support@quickbox.delivery',
        'phone' => '+380 67 010 20 30',
        'address' => 'Івано-Франківськ, вул. Незалежності, 76',
        'about' => 'Міська доставка для магазинів і маркетплейсів.',
    ],
    'tutorspace-academy' => [
        'name' => 'TutorSpace Academy',
        'city' => 'Тернопіль',
        'district' => 'Центральний район',
        'reviews_count' => 71,
        'rating' => 4.9,
        'recommend_percent' => 92,
        'verified' => true,
        'pro' => true,
        'website' => 'tutorspace.ua',
        'email' => 'info@tutorspace.ua',
        'phone' => '+380 67 121 31 41',
        'address' => 'Тернопіль, вул. Руська, 17',
        'about' => 'Освітня платформа з груповими та індивідуальними програмами.',
    ],
    'buildcraft-studio' => [
        'name' => 'BuildCraft Studio',
        'city' => 'Чернігів',
        'district' => 'Деснянський район',
        'reviews_count' => 39,
        'rating' => 4.4,
        'recommend_percent' => 77,
        'verified' => false,
        'pro' => false,
        'website' => 'buildcraft.pro',
        'email' => 'office@buildcraft.pro',
        'phone' => '+380 67 212 32 42',
        'address' => 'Чернігів, вул. Київська, 9',
        'about' => 'Студія ремонту та дизайну інтерʼєрів для квартир і комерційних приміщень.',
    ],
];
