server {
    listen 80;
    listen [::]:80;
    server_name example.com www.example.com;

    root /var/www/dovira/current/public;
    index index.php index.html;

    access_log /var/log/nginx/dovira.access.log;
    error_log /var/log/nginx/dovira.error.log warn;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_read_timeout 1800;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
