<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Support\Str;

final class ProfileSeo
{
    private const TITLE_MAX_LENGTH = 68;
    private const DESCRIPTION_MAX_LENGTH = 160;

    /**
     * @param  array<int, string>  $services
     */
    public static function defaultTitle(
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null
    ): string {
        $name = self::normalizeText($name) ?: 'Профіль DOVIRA';
        $keyword = self::categoryKeyword($categoryName);
        $city = self::normalizeText($city);
        $nameHasKeyword = $keyword !== null && self::nameContainsKeyword($name, $keyword);

        $candidates = array_values(array_filter([
            $keyword !== null && $city !== null && ! $nameHasKeyword ? "Відгуки про {$name} — {$keyword}, {$city} | DOVIRA" : null,
            $city !== null ? "Відгуки про {$name} — {$city} | DOVIRA" : null,
            $keyword !== null && ! $nameHasKeyword ? "Відгуки про {$name} — {$keyword} | DOVIRA" : null,
            "Відгуки про {$name} | DOVIRA",
            "{$name} | DOVIRA",
        ]));

        foreach ($candidates as $candidate) {
            if (mb_strlen($candidate) <= self::TITLE_MAX_LENGTH) {
                return $candidate;
            }
        }

        return Str::limit($candidates[0] ?? "{$name} | DOVIRA", self::TITLE_MAX_LENGTH, '...');
    }

    /**
     * @param  array<int, string>  $services
     */
    public static function defaultDescription(
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null,
        array $services = [],
        ?string $shortDescription = null,
        ?string $description = null
    ): string {
        $name = self::normalizeText($name) ?: 'Профіль DOVIRA';
        $keyword = self::categoryKeyword($categoryName);
        $city = self::normalizeText($city);
        $aboutSentence = self::buildAboutSentence($shortDescription, $description);
        $reviewLeadSentence = self::buildReviewLeadSentence($name, $keyword, $city);
        $profileSentence = self::buildProfileSentence($name, $services, $aboutSentence);
        $supportingSentence = self::profileSentenceHasCallToAction($profileSentence)
            ? null
            : self::supportingSeoSentence($keyword);

        $segments = array_values(array_filter([
            $reviewLeadSentence,
            $profileSentence,
            $supportingSentence,
        ]));

        $result = self::joinSegmentsWithinLimit($segments, self::DESCRIPTION_MAX_LENGTH);

        return $result !== ''
            ? $result
            : Str::limit($name . ' на DOVIRA.', self::DESCRIPTION_MAX_LENGTH, '...');
    }

    /**
     * @param  array<int, string>  $services
     */
    public static function resolvedTitle(
        ?string $storedValue,
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null
    ): string {
        $generated = self::defaultTitle($name, $categoryName, $city);
        $storedValue = self::normalizeText($storedValue);

        if ($storedValue === null || self::isAutoGeneratedTitle($storedValue, $name, $categoryName, $city)) {
            return $generated;
        }

        return $storedValue;
    }

    /**
     * @param  array<int, string>  $services
     */
    public static function resolvedDescription(
        ?string $storedValue,
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null,
        array $services = [],
        ?string $shortDescription = null,
        ?string $description = null
    ): string {
        $generated = self::defaultDescription($name, $categoryName, $city, $services, $shortDescription, $description);
        $storedValue = self::normalizeText($storedValue);

        if ($storedValue === null || self::isAutoGeneratedDescription($storedValue, $name, $categoryName, $city, $services, $shortDescription, $description)) {
            return $generated;
        }

        return $storedValue;
    }

    /**
     * Видимий на сторінці самодостатній абзац-відповідь (40–60 слів): те, що
     * AI-пошук цитує дослівно на запит «[назва] відгуки». Будується детерміновано
     * зі структурних полів — без AI-токенів, покриває будь-який профіль.
     *
     * @param  array<int, string>  $services
     */
    public static function answerParagraph(
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null,
        array $services = [],
        bool $ratingVisible = false,
        float $rating = 0.0,
        int $reviewsCount = 0
    ): string {
        $name = self::normalizeText($name) ?: 'Профіль DOVIRA';
        $keyword = self::categoryKeyword($categoryName);
        $cityPhrase = self::cityLocativePhrase($city);
        $nameHasKeyword = $keyword !== null && self::nameContainsKeyword($name, $keyword);

        // Речення 1: хто це і де.
        $descriptor = $keyword !== null && ! $nameHasKeyword ? " — {$keyword}" : '';
        $where = $cityPhrase !== null ? " {$cityPhrase}" : '';
        $sentence1 = self::ensureSentence(trim("{$name}{$descriptor}{$where}"));

        // Речення 2: оцінка / відгуки (числа, які цінує AI-цитування).
        if ($ratingVisible && $rating > 0 && $reviewsCount > 0) {
            $sentence2 = 'Рейтинг ' . self::formatRatingValue($rating) . ' з 5 — '
                . $reviewsCount . ' ' . self::reviewsWord($reviewsCount) . ' на DOVIRA.';
        } elseif ($reviewsCount > 0) {
            $sentence2 = 'Оцінка ще формується — ' . $reviewsCount . ' '
                . self::reviewsWord($reviewsCount) . ' на DOVIRA.';
        } else {
            $sentence2 = 'Профіль на DOVIRA — залиште перший відгук про свій досвід.';
        }

        // Речення 3: основні напрями (послуги), якщо є.
        $serviceNames = self::serviceNames($services);
        $sentence3 = $serviceNames->isNotEmpty()
            ? 'Основні напрями: ' . $serviceNames->implode(', ') . '.'
            : null;

        return trim(implode(' ', array_filter([$sentence1, $sentence2, $sentence3])));
    }

    /**
     * Пluralізація «відгук / відгуки / відгуків» — та сама, що на сторінці профілю.
     */
    public static function reviewsWord(int $count): string
    {
        $mod10 = $count % 10;
        $mod100 = $count % 100;

        if ($mod10 === 1 && $mod100 !== 11) {
            return 'відгук';
        }

        if (in_array($mod10, [2, 3, 4], true) && ! in_array($mod100, [12, 13, 14], true)) {
            return 'відгуки';
        }

        return 'відгуків';
    }

    /**
     * «4.8» без хвостового нуля («5.0» → «5»), щоб у прозі читалося природно.
     */
    private static function formatRatingValue(float $rating): string
    {
        $formatted = number_format($rating, 1, '.', '');

        return str_ends_with($formatted, '.0') ? substr($formatted, 0, -2) : $formatted;
    }

    public static function isAutoGeneratedTitle(
        ?string $value,
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null
    ): bool {
        $value = self::normalizeComparisonValue($value);

        if ($value === null) {
            return true;
        }

        return in_array($value, collect(self::legacyTitleVariants($name, $categoryName, $city))
            ->merge(self::previousAutoGeneratedTitleVariants($name, $categoryName, $city))
            ->push(self::defaultTitle($name, $categoryName, $city))
            ->map(fn ($item) => self::normalizeComparisonValue($item))
            ->filter()
            ->values()
            ->all(), true);
    }

    /**
     * @param  array<int, string>  $services
     */
    public static function isAutoGeneratedDescription(
        ?string $value,
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null,
        array $services = [],
        ?string $shortDescription = null,
        ?string $description = null
    ): bool {
        $value = self::normalizeComparisonValue($value);

        if ($value === null) {
            return true;
        }

        return in_array($value, collect(self::legacyDescriptionVariants($name, $categoryName, $city))
            ->merge(self::previousAutoGeneratedDescriptionVariants($name, $categoryName, $city, $services, $shortDescription, $description))
            ->push(self::defaultDescription($name, $categoryName, $city, $services, $shortDescription, $description))
            ->map(fn ($item) => self::normalizeComparisonValue($item))
            ->filter()
            ->values()
            ->all(), true);
    }

    /**
     * @return array<int, string>
     */
    private static function legacyTitleVariants(?string $name, ?string $categoryName = null, ?string $city = null): array
    {
        $name = self::normalizeText($name) ?: 'Профіль';
        $city = self::normalizeText($city);

        return array_values(array_filter([
            "{$name}" . ($city ? " {$city}" : '') . ' — відгуки, контакти, інформація | DOVIRA',
            $categoryName ? "{$name} — " . mb_strtolower((string) $categoryName) . ($city ? " в {$city}" : '') . ' | DOVIRA' : null,
            "{$name} — DOVIRA",
        ]));
    }

    /**
     * @return array<int, string>
     */
    private static function previousAutoGeneratedTitleVariants(?string $name, ?string $categoryName = null, ?string $city = null): array
    {
        $name = self::normalizeText($name) ?: 'Профіль DOVIRA';
        $keyword = self::categoryKeyword($categoryName);
        $city = self::normalizeText($city);
        $nameHasKeyword = $keyword !== null && self::nameContainsKeyword($name, $keyword);

        return array_values(array_filter([
            $keyword !== null && $city !== null && ! $nameHasKeyword ? "{$name} — {$keyword}, {$city} | DOVIRA" : null,
            $city !== null ? "{$name} — {$city}: відгуки, контакти | DOVIRA" : null,
            $keyword !== null && ! $nameHasKeyword ? "{$name} — {$keyword}: відгуки, контакти | DOVIRA" : null,
            "{$name} — відгуки, контакти | DOVIRA",
            "{$name} | DOVIRA",
        ]));
    }

    /**
     * @return array<int, string>
     */
    private static function legacyDescriptionVariants(?string $name, ?string $categoryName = null, ?string $city = null): array
    {
        $name = self::normalizeText($name) ?: 'Профіль';
        $categoryName = self::normalizeCategoryName($categoryName);
        $city = self::normalizeText($city);

        return array_values(array_filter([
            'Інформація про ' . $name . ($city ? ' у місті ' . $city : '') . ': контакти, джерела, відгуки та репутація на DOVIRA.',
            trim(collect([
                $name,
                $categoryName ? '— ' . mb_strtolower($categoryName) : null,
                $city ? 'у ' . $city : null,
            ])->filter()->implode(' ') . '. Контакти, адреса, відгуки та детальна інформація на DOVIRA.'),
            'Профіль на DOVIRA',
        ]));
    }

    /**
     * @return array<int, string>
     */
    private static function previousAutoGeneratedDescriptionVariants(
        ?string $name,
        ?string $categoryName = null,
        ?string $city = null,
        array $services = [],
        ?string $shortDescription = null,
        ?string $description = null
    ): array {
        $name = self::normalizeText($name) ?: 'Профіль';
        $keyword = self::categoryKeyword($categoryName);
        $city = self::normalizeText($city);
        $nameHasKeyword = $keyword !== null && self::nameContainsKeyword($name, $keyword);
        $rawAbout = self::rawAboutText($shortDescription, $description);
        $oldSearchDescription = self::previousSearchGeneratedDescription($name, $keyword, $city, $services, $shortDescription, $description);

        return array_values(array_filter([
            $keyword !== null && $city !== null && ! $nameHasKeyword ? "{$name} — {$keyword}, {$city}." : null,
            $city !== null ? "{$name} — {$city}." : null,
            $keyword !== null && ! $nameHasKeyword ? "{$name} — {$keyword}." : null,
            $keyword !== null && $city !== null && ! $nameHasKeyword && $rawAbout !== null ? "{$name} — {$keyword}, {$city}. {$rawAbout}" : null,
            $city !== null && $rawAbout !== null ? "{$name} — {$city}. {$rawAbout}" : null,
            $keyword !== null && ! $nameHasKeyword && $rawAbout !== null ? "{$name} — {$keyword}. {$rawAbout}" : null,
            $oldSearchDescription,
        ]));
    }

    private static function previousSearchGeneratedDescription(
        string $name,
        ?string $keyword,
        ?string $city,
        array $services,
        ?string $shortDescription,
        ?string $description
    ): ?string {
        $searchSentence = self::buildSearchSentence($keyword, $city);
        $profileSentence = self::buildPreviousSearchProfileSentence($name, $services, self::buildAboutSentence($shortDescription, $description));

        return self::joinSegmentsWithinLimit(array_values(array_filter([
            $searchSentence,
            $profileSentence,
            self::previousSearchSupportingSeoSentence($keyword),
        ])), self::DESCRIPTION_MAX_LENGTH) ?: null;
    }

    private static function buildAboutSentence(?string $shortDescription, ?string $description): ?string
    {
        $source = self::rawAboutText($shortDescription, $description);

        if ($source === null) {
            return null;
        }

        if (mb_strlen($source) < 32 || self::isLikelyPlaceholderText($source)) {
            return null;
        }

        $source = preg_replace('/\s+/u', ' ', $source);
        $source = preg_replace('/\s*([,.!?;:])\s*/u', '$1 ', $source);
        $source = trim((string) $source);

        return self::ensureSentence(Str::limit($source, 92, '...'));
    }

    private static function rawAboutText(?string $shortDescription, ?string $description): ?string
    {
        return self::normalizeText($shortDescription)
            ?: self::normalizeText($description);
    }

    private static function buildSearchSentence(?string $keyword, ?string $city): ?string
    {
        $cityPhrase = self::cityLocativePhrase($city);

        return match (mb_strtolower((string) $keyword)) {
            'адвокат' => $cityPhrase !== null ? "Шукаєте адвоката {$cityPhrase}?" : 'Шукаєте адвоката?',
            'юрист' => $cityPhrase !== null ? "Потрібен юрист {$cityPhrase}?" : 'Потрібен юрист?',
            'стоматолог' => $cityPhrase !== null ? "Шукаєте стоматолога {$cityPhrase}?" : 'Шукаєте стоматолога?',
            'нотаріус' => $cityPhrase !== null ? "Потрібен нотаріус {$cityPhrase}?" : 'Потрібен нотаріус?',
            'спеціаліст' => $cityPhrase !== null ? "Шукаєте спеціаліста {$cityPhrase}?" : 'Шукаєте спеціаліста?',
            'компанія', 'магазин', 'сервіс' => $cityPhrase !== null ? "Шукаєте компанію {$cityPhrase}?" : 'Шукаєте компанію?',
            default => $cityPhrase !== null ? "Перегляньте профіль {$cityPhrase}." : null,
        };
    }

    private static function buildReviewLeadSentence(string $name, ?string $keyword, ?string $city): string
    {
        $cityPhrase = self::cityLocativePhrase($city);
        $nameHasKeyword = $keyword !== null && self::nameContainsKeyword($name, $keyword);
        $context = $keyword !== null && ! $nameHasKeyword
            ? ', ' . self::keywordGenitive($keyword)
            : '';

        if ($cityPhrase !== null) {
            return "Відгуки про {$name}{$context} {$cityPhrase}.";
        }

        return "Відгуки про {$name}{$context} на DOVIRA.";
    }

    /**
     * @param  array<int, string>  $services
     */
    private static function buildProfileSentence(string $name, array $services, ?string $aboutSentence): string
    {
        if ($aboutSentence !== null) {
            return $aboutSentence;
        }

        $serviceNames = self::serviceNames($services);

        if ($serviceNames->isNotEmpty()) {
            return self::ucfirstSentence($serviceNames->implode(', ')) . '. Контакти на DOVIRA.';
        }

        return 'Перевірте репутацію, контакти та досвід клієнтів.';
    }

    /**
     * @param  array<int, string>  $services
     */
    private static function buildPreviousSearchProfileSentence(string $name, array $services, ?string $aboutSentence): string
    {
        if ($aboutSentence !== null) {
            return "{$name}: {$aboutSentence}";
        }

        $serviceNames = self::serviceNames($services);

        if ($serviceNames->isNotEmpty()) {
            return "{$name}: " . $serviceNames->implode(', ') . '. Контакти й відгуки на DOVIRA.';
        }

        return "{$name}: інформація про профіль, контакти та репутацію.";
    }

    /**
     * @param  array<int, string>  $services
     */
    private static function serviceNames(array $services): \Illuminate\Support\Collection
    {
        return collect($services)
            ->map(fn ($service) => self::normalizeText(is_string($service) ? $service : null))
            ->filter()
            ->unique(fn ($service) => mb_strtolower((string) $service))
            ->take(3)
            ->map(fn ($service) => self::lowercaseSentenceItem((string) $service))
            ->values();
    }

    /**
     * @param  array<int, string>  $segments
     */
    private static function joinSegmentsWithinLimit(array $segments, int $limit): string
    {
        $result = '';

        foreach ($segments as $segment) {
            $segment = self::normalizeText($segment);
            if ($segment === null) {
                continue;
            }

            $candidate = trim($result === '' ? $segment : "{$result} {$segment}");

            if (mb_strlen($candidate) <= $limit) {
                $result = $candidate;
                continue;
            }

            if ($result === '') {
                $result = Str::limit($segment, $limit, '...');
            }

            break;
        }

        return $result;
    }

    private static function categoryKeyword(?string $categoryName): ?string
    {
        $normalized = self::normalizeCategoryName($categoryName);
        if ($normalized === null) {
            return null;
        }

        return match ($normalized) {
            'Адвокати' => 'адвокат',
            'Юристи' => 'юрист',
            'Стоматологи' => 'стоматолог',
            'Нотаріуси' => 'нотаріус',
            'Компанії' => 'компанія',
            'Магазини' => 'магазин',
            'Сервіси' => 'сервіс',
            'Спеціалісти' => 'спеціаліст',
            'Lawyers' => 'lawyer',
            'Dentists' => 'dentist',
            'Notaries' => 'notary',
            default => mb_strtolower($normalized),
        };
    }

    private static function keywordGenitive(string $keyword): string
    {
        return match (mb_strtolower($keyword)) {
            'адвокат' => 'адвоката',
            'юрист' => 'юриста',
            'стоматолог' => 'стоматолога',
            'нотаріус' => 'нотаріуса',
            'компанія', 'компанія ' => 'компанії',
            'магазин' => 'магазину',
            'сервіс' => 'сервісу',
            'спеціаліст' => 'спеціаліста',
            default => $keyword,
        };
    }

    private static function supportingSeoSentence(?string $keyword): string
    {
        return match (mb_strtolower((string) $keyword)) {
            'адвокат', 'юрист', 'стоматолог', 'нотаріус', 'спеціаліст' => 'Читайте досвід клієнтів на DOVIRA.',
            'компанія', 'магазин', 'сервіс' => 'Читайте досвід клієнтів про компанію на DOVIRA.',
            default => 'Читайте досвід клієнтів на DOVIRA.',
        };
    }

    private static function previousSearchSupportingSeoSentence(?string $keyword): string
    {
        return match (mb_strtolower((string) $keyword)) {
            'адвокат', 'юрист', 'стоматолог', 'нотаріус', 'спеціаліст' => 'Дивіться контакти, відгуки клієнтів і деталі профілю.',
            'компанія', 'магазин', 'сервіс' => 'Дивіться контакти, відгуки клієнтів і деталі компанії.',
            default => 'Дивіться контакти, відгуки та деталі профілю.',
        };
    }

    private static function profileSentenceHasCallToAction(string $sentence): bool
    {
        return Str::contains(mb_strtolower($sentence), ['контакти', 'відгуки']);
    }

    private static function cityLocativePhrase(?string $city): ?string
    {
        $city = self::normalizeText($city);

        if ($city === null) {
            return null;
        }

        $normalized = mb_strtolower($city);
        $locative = match ($normalized) {
            'київ' => 'Києві',
            'одеса' => 'Одесі',
            'львів' => 'Львові',
            'харків' => 'Харкові',
            'дніпро' => 'Дніпрі',
            'запоріжжя' => 'Запоріжжі',
            'вінниця' => 'Вінниці',
            'полтава' => 'Полтаві',
            'черкаси' => 'Черкасах',
            'чернігів' => 'Чернігові',
            'суми' => 'Сумах',
            'рівне' => 'Рівному',
            'житомир' => 'Житомирі',
            'луцьк' => 'Луцьку',
            'ужгород' => 'Ужгороді',
            'івано-франківськ' => 'Івано-Франківську',
            'тернопіль' => 'Тернополі',
            'хмельницький' => 'Хмельницькому',
            'чернівці' => 'Чернівцях',
            'миколаїв' => 'Миколаєві',
            'херсон' => 'Херсоні',
            'кропивницький' => 'Кропивницькому',
            default => null,
        };

        if ($locative === null) {
            return "у місті {$city}";
        }

        return (Str::startsWith(mb_strtolower($locative), ['о', 'і', 'а', 'е', 'у', 'я', 'ю', 'є', 'ї'])
            ? 'в '
            : 'у ') . $locative;
    }

    private static function nameContainsKeyword(string $name, string $keyword): bool
    {
        $normalizedName = mb_strtolower($name);
        $normalizedKeyword = mb_strtolower($keyword);

        if (Str::contains($normalizedName, $normalizedKeyword)) {
            return true;
        }

        return match ($normalizedKeyword) {
            'адвокат' => Str::contains($normalizedName, ['адвокат', 'адвокатка']),
            'юрист' => Str::contains($normalizedName, ['юрист', 'юридич']),
            'стоматолог' => Str::contains($normalizedName, ['стоматолог', 'стоматологія']),
            'нотаріус' => Str::contains($normalizedName, ['нотаріус', 'нотаріальна']),
            default => false,
        };
    }

    private static function ensureSentence(string $value): string
    {
        $value = trim($value);

        if ($value === '') {
            return $value;
        }

        if (preg_match('/[.!?…]$/u', $value) === 1) {
            return $value;
        }

        return $value . '.';
    }

    private static function normalizeText(?string $value): ?string
    {
        $plain = html_entity_decode(strip_tags((string) $value), ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $normalized = preg_replace('/\s+/u', ' ', trim($plain));

        return $normalized === '' ? null : $normalized;
    }

    private static function normalizeCategoryName(?string $value): ?string
    {
        $normalized = self::normalizeText($value);

        if ($normalized === null || $normalized === 'Без категорії') {
            return null;
        }

        return $normalized;
    }

    private static function normalizeComparisonValue(?string $value): ?string
    {
        $normalized = self::normalizeText($value);

        return $normalized === null ? null : mb_strtolower($normalized);
    }

    private static function lowercaseSentenceItem(string $value): string
    {
        $first = mb_substr($value, 0, 1);

        if (preg_match('/^[А-ЯІЇЄҐ]$/u', $first) !== 1) {
            return $value;
        }

        return mb_strtolower($first) . mb_substr($value, 1);
    }

    private static function ucfirstSentence(string $value): string
    {
        $first = mb_substr($value, 0, 1);

        return mb_strtoupper($first) . mb_substr($value, 1);
    }

    private static function isLikelyPlaceholderText(string $value): bool
    {
        return preg_match('/(?:\btest\b|\bdemo\b|lorem ipsum|placeholder|заглуш|тестов|для перевірк|перевірк(?:а|и)? збереженн)/iu', $value) === 1;
    }
}
